config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new,:create, :show]
  resources :bands
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    before_validation :ensure_session_token
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum:6}, allow_nil: true
    attr_reader :password

    def self.finy_by_credentials(email,password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end

    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(password)
    end
    
    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save
        self.session_token
    end

    def generate_unique_session_token
        while true
            session_token = SecureRandom::urlsafe_base64
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token

    end

    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_login

    end

    def require_logout

    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]

    def index
        @bands = Band.all
        :index
    end

    def new
        :new
    end

    def show
        @band = Band.find_by(id: params[:id])
        :show
    end

    def create 
        band = Band.new(band_params)
        if band.save!
            redirect_to bands_url
        else
            redirect_to :new
        end

    end

    def edit
        @band = Band.find_by(id: params[:id])
        :edit
    end

    def update
        band = Band.find_by(id: params[:id])
        if band.update(band_params)
            redirect_to bands_url
        else
            redirect_to band_url(band)
        end
    end

    def destroy
        band = Band.find_by(id: params[:id])
        band.destroy
        redirect_to bands_url
    end

    def set_band
        @band = Band.find_by(id: params[:id])
    end
    
    private
    
    def band_params
        params.require(:band).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.finy_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to bands_url
        else
            flash.now[:errors] = ['Not user found with that username or password']
            render user_url(@user)
        end

    end

    def destroy
        logout!
        redirect_to bands_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to bands_url
        else    
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
        
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def destroy
        @user = User.find_by(id: params[:id])
        @user.destroy
        redirect_to users_url
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/_partial.html.erb
<ul>
    <li>Band name: <%= bandname.name%> </li>
</ul>

app/views/bands/edit.html.erb
<h1>Change Band Name</h1>

<form action="<%= band_url(@band) %>" method="POST">
<input type='hidden' name='_method' value='PATCH' >
    <label>Current Band Name: <%= @band.name %> </label>
    <br>
  <label for="name">Change Band Name To:</label>
  <input type="text" name="band[name]" id="name" value=""> 
  <br>
  <input type="submit" value="Change">
</form>

app/views/bands/index.html.erb
Bands Index Page
<br>

<ul>
  <a href='<%= new_band_url %>'> Register a band </a>
  <br>
  <br>
  <% @bands.each do |band| %>
  <li>
    <%= render 'partial', bandname: band %>
  </li>
  <br>
  <a href="<%= band_url(band) %>">Show Band</a>
  <form action='<%= band_url(band) %>' method='POST'>
  <input type='hidden' name='_method' value='DELETE'>
  <input type='submit' value='Delete Band'>
  </form>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>New Band Form</h1>

<form action="<%= bands_url %>" method="POST">

  <label for="email">Band Name:</label>
  <input type="text" name="band[name]" id="name" value=""> 
  <br>
  <input type="submit" value="Register">
</form>

app/views/bands/show.html.erb
<table>
    <td>
    <tr>
     <%= render 'partial', bandname: @band %>
     </tr>
    </td>
    <td>
    <tr>
        <a href="<%= edit_band_url(@band) %>">Change Name</a>
    </tr>
    <tr>
        <form action='<%= band_url %>' method='POST'>
          <input type='hidden' name='_method' value='DELETE'>
          <input type='submit' value='Delete Band'>
        </form>
    </tr>
    </td>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <h1 class='title'>MusicApp</h1>
      <div class='login'>
      <% if logged_in? %>
        <h1> Welcome <%= current_user.email %> </h1>
        <form action='<%= session_url %>' method='POST'>
          <input type='hidden' name='_method' value='DELETE'>
          <input type='submit' value='Logout'>
        </form>
      <% else %>
        <a href='<%=new_session_url%>' >Login</a>  
        <a href='<%=new_user_url%>' >Sign Up</a>  
      <% end %>
      </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up form</h1>

<form action="<%= users_url %>" method="POST">

  <label for="email">Email:</label>
  <input type="text" name="user[email]" id="email" value="">
  <br>
  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  
  <br>
  <input type="submit" value="Sign up">
</form>